services:
  core-vault-management:
    image: ${CI_REGISTRY_IMAGE}:${DEPLOY_IMAGE_TAG}
    network_mode: host
    command: ["bash", "entrypoint.sh", "run"]
    restart: unless-stopped
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RPC_URL: ${RPC_URL}
      RPC_API_KEY: ${RPC_API_KEY}
      NODE_PATH: /usr/local/bin/node
      FASSET_BOT_CONFIG: /var/fasset/config.bot.json
      FASSET_BOT_SECRETS: /var/fasset/secrets.bot.json
      FASSET_USER_CONFIG: /var/fasset/config.user.json
      FASSET_USER_SECRETS: /var/fasset/secrets.user.json
      CONFIG: /app/config.toml
    volumes:
      - ${FASSET_BOT_CONFIG}:/var/fasset/config.bot.json
      - ${FASSET_BOT_SECRETS}:/var/fasset/secrets.bot.json
      - ${FASSET_USER_CONFIG}:/var/fasset/config.user.json
      - ${FASSET_USER_SECRETS}:/var/fasset/secrets.user.json
      - ${CONFIG}:/app/config.toml
